### ISSUE TITLE
BoxOAuth revoke_token must call self.token_storage.clear()

### ISSUE THREAD

**Issue by LesPrimus** [box/box-python-sdk-gen#339]
Hi

I implemented a custom storage as per documentation.

```
from box_sdk_gen import BoxOAuth, OAuthConfig

class MyCustomTokenStorage(TokenStorage):
        def clear(self) -> None:
            print("Called clear ")

auth = BoxOAuth(
    OAuthConfig(
        client_id="YOUR_CLIENT_ID",
        client_secret="YOUR_CLIENT_SECRET",
        token_storage=MyCustomTokenStorage(),
    )
)
```
But the clear method in MyCustomStorage isn't called by BoxOauth.revoke_token()
```
client.auth.revoke_token()
```

Perhaps BoxOauth revoke_token must call

 ```self.token_storage.clear()```

**Comment by lukaszsocha2** [comment]
Hi @LesPrimus,
thanks for reaching us. Clearing a token storage is not called, because this would clear refresh token as well. Then getting a new token would require repeating the entire auth process, instead using a refresh token may be utilized to get a new one. If you want to remove also refresh token from token storage I recommend to call `self.token_storage.clear()` right after revoking the token.
Best,
@lukaszsocha2
