### ISSUE TITLE
client.shared_links_files.get_shared_link_for_file does not return the shared link.

### ISSUE THREAD

**Issue by arkp1612** [box/box-python-sdk-gen#343]
Hi, 

I am trying to get the share link of the file id. I get a response but it does not have the share link.

**Input:** client.shared_links_files.get_shared_link_for_file('123', fields='shared_link')
**Output:** <class 'box_sdk_gen.schemas.file_full.FileFull'> {'id': '123', 'etag': '0', 'type': 'file'} 

What is missing?

**Comment by lukaszsocha2** [comment]
Hi @arkp1612,
can you try to tun the scenario similar to the one in this test: https://github.com/box/box-python-sdk-gen/blob/main/test/shared_links_files.py? This is one of our integration test, which is run on each commit. If the scenario fails for you let us know, that would mean that most likely the problem is with your Box account permissions, not the code itself.
Best,
@lukaszsocha2

**Comment by arkp1612** [comment]
Hi, managed to do it now. I did not realize we needed to update the share link for each file and though they would be there by default. 

The following works - 

```
client.files.update_file_by_id(item.id, shared_link={})
print(client.files.get_file_by_id(item.id,fields='shared_link'))
```

**Comment by arkp1612** [comment]
Hi, managed to do it now. I did not realize we needed to update the share link for each file and though they would be there by default. 

The following works - 

```
client.files.update_file_by_id(item.id, shared_link={})
print(client.files.get_file_by_id(item.id,fields='shared_link'))
```
